services:
  - type: web
    name: gridironcards
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt && chmod +x start.sh
    startCommand: ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
